### ISSUE TITLE
Not compatible with ruby 3.2

### ISSUE THREAD

**Issue by gleonet** [eregon/path#21]
Hi,

As the methods `Object#taint, #untaint, #tainted?, #trust, #untrust, #untrusted?` have been removed from Ruby 3.2 (deprecated since Ruby 2.7), projects using `path` cannot be upgrade to use Ruby 3.2.

Best regards

**Comment by eregon** [comment]
This was fixed in 8dbda0b0f48463aa8b1293d86f8398c51a6b163e but there was no release since then. I'll try to make one.
Also RSpec 2 doesn't support Ruby 3.2, so I updated to RSpec 3.

**Comment by eregon** [comment]
https://rubygems.org/gems/path/versions/2.1.0
